### ISSUE TITLE
项目启动

### ISSUE THREAD

**Issue by IsDreame** [lhccong/LunarSurvey#1]
这个前端代码没有开源吗

**Comment by lhccong** [comment]
有的，https://github.com/lhccong/LunarSurvey-frontend

**Comment by IsDreame** [comment]
![image](https://github.com/user-attachments/assets/b98c14c9-cab1-48bb-af5d-cdf3546a5015)
这个是没有配置 ai 的key 吗

**Comment by IsDreame** [comment]
还有前端这么多错误是什么
![image](https://github.com/user-attachments/assets/6a67ef47-3314-4f76-9221-c6d08df16f92)

**Comment by lhccong** [comment]
> ![image](https://private-user-images.githubusercontent.com/87373971/365430225-b98c14c9-cab1-48bb-af5d-cdf3546a5015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTIxMTQsIm5iZiI6MTcyNTg1MTgxNCwicGF0aCI6Ii84NzM3Mzk3MS8zNjU0MzAyMjUtYjk4YzE0YzktY2FiMS00OGJiLWFmNWQtY2RmMzU0NmE1MDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzMTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMTNiNzkwNWNmZDViNGM0MWE0OWRmNzkyNzJhYWZlY2EzNjNmMmM0MDNiMDBlZmI1MjRmNmViY2Q0YjdmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3vLAgcEX79J6AnyDNIUjxg8S10OZEU4IG7PyiLmT53E) 这个是没有配置 ai 的key 吗

是的

**Comment by lhccong** [comment]
> 还有前端这么多错误是什么 ![image](https://private-user-images.githubusercontent.com/87373971/365430298-6a67ef47-3314-4f76-9221-c6d08df16f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTIxMTQsIm5iZiI6MTcyNTg1MTgxNCwicGF0aCI6Ii84NzM3Mzk3MS8zNjU0MzAyOTgtNmE2N2VmNDctMzMxNC00Zjc2LTkyMjEtYzZkMDhkZjE2ZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzMTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDc1ZmViMjUyOGM0YjFmYTA1Y2FiM2JjNzgxNzA3NTMzMmM1YWIwMzBjMmUxYmNhODQ4YmFmYmE5ZTNjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xeYRin2RTlKsQhoIhDYb4lgbTEU0X-5ijVEIaBzLiOk)

这个可能是代码写的时候没有用格式化插件，你引用了导致的错误，将代码格式化一下或者关闭格式化校验
